### PR TITLE
Add offline mode support

### PR DESCRIPTION
**Pull request by BasiqueEvangelist**

### CODE REVIEW

**Comment by Gappysona** [comment]
Ooh yes! Local avatars in offline mode?

**Comment by Gappysona** [comment]
Wait- correction...

**Comment by Gappysona** [comment]
Okay my brain is fried today. Anyway, Zandra has said that offline support is not coming due to the fact that people can impersonate others and then therefore upload an avatar under their name.

**Comment by BasiqueEvangelist** [comment]
This will *not* be used in production. I made this PR only to help make testing changes to the backend easier.

**Comment by TheOneTrueZandra** [comment]
Yeah, this is a debug-only feature for development. The released backend will not support this.

**Pull request merged**
